<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output omit-xml-declaration="yes"/>
	<xsl:template match="@*|node()">
		<xsl:copy>
			<xsl:apply-templates select="@*|node()"/>
		</xsl:copy>
	</xsl:template>
  	<!-- Minor Leaders -->
	<xsl:template match="EquipmentRoster[@id='spc_skolderbrotva_leader_0']"/>
	<xsl:template match="EquipmentRoster[@id='spc_skolderbrotva_leader_1']"/>
	<xsl:template match="EquipmentRoster[@id='spc_skolderbrotva_leader_2']"/>
	<xsl:template match="EquipmentRoster[@id='spc_skolderbrotva_leader_3']"/>
	<xsl:template match="EquipmentRoster[@id='spc_ghilman_leader_0']"/>
	<xsl:template match="EquipmentRoster[@id='spc_ghilman_leader_1']"/>
	<xsl:template match="EquipmentRoster[@id='spc_ghilman_leader_2']"/>
	<xsl:template match="EquipmentRoster[@id='spc_ghilman_leader_3']"/>
	<xsl:template match="EquipmentRoster[@id='spc_legion_of_the_betrayed_leader_0']"/>
	<xsl:template match="EquipmentRoster[@id='spc_legion_of_the_betrayed_leader_1']"/>
	<xsl:template match="EquipmentRoster[@id='spc_legion_of_the_betrayed_leader_2']"/>
	<xsl:template match="EquipmentRoster[@id='spc_legion_of_the_betrayed_leader_3']"/>
	<xsl:template match="EquipmentRoster[@id='spc_company_of_the_boar_leader_0']"/>
	<xsl:template match="EquipmentRoster[@id='spc_company_of_the_boar_leader_1']"/>
	<xsl:template match="EquipmentRoster[@id='spc_company_of_the_boar_leader_2']"/>
	<xsl:template match="EquipmentRoster[@id='spc_company_of_the_boar_leader_3']"/>
	<xsl:template match="EquipmentRoster[@id='spc_wolfskins_leader_0']"/>
	<xsl:template match="EquipmentRoster[@id='spc_wolfskins_leader_1']"/>
	<xsl:template match="EquipmentRoster[@id='spc_wolfskins_leader_2']"/>
	<xsl:template match="EquipmentRoster[@id='spc_wolfskins_leader_3']"/>
	<xsl:template match="EquipmentRoster[@id='spc_beni_zilal_leader_0']"/>
	<xsl:template match="EquipmentRoster[@id='spc_beni_zilal_leader_1']"/>
	<xsl:template match="EquipmentRoster[@id='spc_beni_zilal_leader_2']"/>
	<xsl:template match="EquipmentRoster[@id='spc_beni_zilal_leader_3']"/>
	<xsl:template match="EquipmentRoster[@id='spc_brotherhood_of_woods_leader_0']"/>
	<xsl:template match="EquipmentRoster[@id='spc_brotherhood_of_woods_leader_1']"/>
	<xsl:template match="EquipmentRoster[@id='spc_brotherhood_of_woods_leader_2']"/>
	<xsl:template match="EquipmentRoster[@id='spc_brotherhood_of_woods_leader_3']"/>
	<xsl:template match="EquipmentRoster[@id='spc_chosen_of_the_sky_leader_0']"/>
	<xsl:template match="EquipmentRoster[@id='spc_chosen_of_the_sky_leader_1']"/>
	<xsl:template match="EquipmentRoster[@id='spc_chosen_of_the_sky_leader_2']"/>
	<xsl:template match="EquipmentRoster[@id='spc_chosen_of_the_sky_leader_3']"/>
	<xsl:template match="EquipmentRoster[@id='spc_lakepike_leader_0']"/>
	<xsl:template match="EquipmentRoster[@id='spc_lakepike_leader_1']"/>
	<xsl:template match="EquipmentRoster[@id='spc_lakepike_leader_2']"/>
	<xsl:template match="EquipmentRoster[@id='spc_lakepike_leader_3']"/>
	<xsl:template match="EquipmentRoster[@id='spc_hidden_hand_leader_0']"/>
	<xsl:template match="EquipmentRoster[@id='spc_hidden_hand_leader_1']"/>
	<xsl:template match="EquipmentRoster[@id='spc_hidden_hand_leader_2']"/>
	<xsl:template match="EquipmentRoster[@id='spc_hidden_hand_leader_3']"/>
	<xsl:template match="EquipmentRoster[@id='spc_embers_of_flame_leader_0']"/>
	<xsl:template match="EquipmentRoster[@id='spc_embers_of_flame_leader_1']"/>
	<xsl:template match="EquipmentRoster[@id='spc_embers_of_flame_leader_2']"/>
	<xsl:template match="EquipmentRoster[@id='spc_embers_of_flame_leader_3']"/>
	<xsl:template match="EquipmentRoster[@id='spc_jawwal_leader_0']"/>
	<xsl:template match="EquipmentRoster[@id='spc_jawwal_leader_1']"/>
	<xsl:template match="EquipmentRoster[@id='spc_jawwal_leader_2']"/>
	<xsl:template match="EquipmentRoster[@id='spc_jawwal_leader_3']"/>
	<xsl:template match="EquipmentRoster[@id='spc_karakhuzaits_leader_0']"/>
	<xsl:template match="EquipmentRoster[@id='spc_karakhuzaits_leader_1']"/>
	<xsl:template match="EquipmentRoster[@id='spc_karakhuzaits_leader_2']"/>
	<xsl:template match="EquipmentRoster[@id='spc_karakhuzaits_leader_3']"/>
	<xsl:template match="EquipmentRoster[@id='spc_forest_people_leader_0']"/>
	<xsl:template match="EquipmentRoster[@id='spc_forest_people_leader_1']"/>
	<xsl:template match="EquipmentRoster[@id='spc_forest_people_leader_2']"/>
	<xsl:template match="EquipmentRoster[@id='spc_forest_people_leader_3']"/>
	<xsl:template match="EquipmentRoster[@id='spc_eleftheroi_leader_0']"/>
	<xsl:template match="EquipmentRoster[@id='spc_eleftheroi_leader_1']"/>
	<xsl:template match="EquipmentRoster[@id='spc_eleftheroi_leader_2']"/>
	<xsl:template match="EquipmentRoster[@id='spc_eleftheroi_leader_3']"/>
</xsl:stylesheet>
